language: c
sudo: true

before_install:
- sudo apt-get update
- sudo apt-get -y install wget
- sudo apt-get -y install unzip

env:
- ARCH=--x86
- ARCH=--amd64
- ARCH=--arm
- ARCH=--mips
- ARCH=--powerpc

script:
- make all
