# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/predator/Documents/Project/temp/libsoundio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/predator/Documents/Project/temp/libsoundio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: all
	$(Q)./CMakeFiles/make.sh 1200 "stat"
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f CMakeFiles/doc.dir/build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named sio_list_devices

# Build rule for target.
sio_list_devices: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sio_list_devices
.PHONY : sio_list_devices

# fast build rule for target.
sio_list_devices/fast:
	$(MAKE) -f CMakeFiles/sio_list_devices.dir/build.make CMakeFiles/sio_list_devices.dir/build
.PHONY : sio_list_devices/fast

#=============================================================================
# Target rules for targets named sio_sine

# Build rule for target.
sio_sine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sio_sine
.PHONY : sio_sine

# fast build rule for target.
sio_sine/fast:
	$(MAKE) -f CMakeFiles/sio_sine.dir/build.make CMakeFiles/sio_sine.dir/build
.PHONY : sio_sine/fast

#=============================================================================
# Target rules for targets named libsoundio_shared

# Build rule for target.
libsoundio_shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libsoundio_shared
.PHONY : libsoundio_shared

# fast build rule for target.
libsoundio_shared/fast:
	$(MAKE) -f CMakeFiles/libsoundio_shared.dir/build.make CMakeFiles/libsoundio_shared.dir/build
.PHONY : libsoundio_shared/fast

#=============================================================================
# Target rules for targets named libsoundio_static

# Build rule for target.
libsoundio_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libsoundio_static
.PHONY : libsoundio_static

# fast build rule for target.
libsoundio_static/fast:
	$(MAKE) -f CMakeFiles/libsoundio_static.dir/build.make CMakeFiles/libsoundio_static.dir/build
.PHONY : libsoundio_static/fast

#=============================================================================
# Target rules for targets named coverage

# Build rule for target.
coverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coverage
.PHONY : coverage

# fast build rule for target.
coverage/fast:
	$(MAKE) -f CMakeFiles/coverage.dir/build.make CMakeFiles/coverage.dir/build
.PHONY : coverage/fast

#=============================================================================
# Target rules for targets named underflow

# Build rule for target.
underflow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 underflow
.PHONY : underflow

# fast build rule for target.
underflow/fast:
	$(MAKE) -f CMakeFiles/underflow.dir/build.make CMakeFiles/underflow.dir/build
.PHONY : underflow/fast

#=============================================================================
# Target rules for targets named sio_microphone

# Build rule for target.
sio_microphone: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sio_microphone
.PHONY : sio_microphone

# fast build rule for target.
sio_microphone/fast:
	$(MAKE) -f CMakeFiles/sio_microphone.dir/build.make CMakeFiles/sio_microphone.dir/build
.PHONY : sio_microphone/fast

#=============================================================================
# Target rules for targets named sio_record

# Build rule for target.
sio_record: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sio_record
.PHONY : sio_record

# fast build rule for target.
sio_record/fast:
	$(MAKE) -f CMakeFiles/sio_record.dir/build.make CMakeFiles/sio_record.dir/build
.PHONY : sio_record/fast

#=============================================================================
# Target rules for targets named unit_tests

# Build rule for target.
unit_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit_tests
.PHONY : unit_tests

# fast build rule for target.
unit_tests/fast:
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/build
.PHONY : unit_tests/fast

#=============================================================================
# Target rules for targets named overflow

# Build rule for target.
overflow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 overflow
.PHONY : overflow

# fast build rule for target.
overflow/fast:
	$(MAKE) -f CMakeFiles/overflow.dir/build.make CMakeFiles/overflow.dir/build
.PHONY : overflow/fast

#=============================================================================
# Target rules for targets named latency

# Build rule for target.
latency: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 latency
.PHONY : latency

# fast build rule for target.
latency/fast:
	$(MAKE) -f CMakeFiles/latency.dir/build.make CMakeFiles/latency.dir/build
.PHONY : latency/fast

#=============================================================================
# Target rules for targets named backend_disconnect_recover

# Build rule for target.
backend_disconnect_recover: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 backend_disconnect_recover
.PHONY : backend_disconnect_recover

# fast build rule for target.
backend_disconnect_recover/fast:
	$(MAKE) -f CMakeFiles/backend_disconnect_recover.dir/build.make CMakeFiles/backend_disconnect_recover.dir/build
.PHONY : backend_disconnect_recover/fast

example/sio_list_devices.o: example/sio_list_devices.c.o

.PHONY : example/sio_list_devices.o

# target to build an object file
example/sio_list_devices.c.o:
	$(MAKE) -f CMakeFiles/sio_list_devices.dir/build.make CMakeFiles/sio_list_devices.dir/example/sio_list_devices.c.o
.PHONY : example/sio_list_devices.c.o

example/sio_list_devices.i: example/sio_list_devices.c.i

.PHONY : example/sio_list_devices.i

# target to preprocess a source file
example/sio_list_devices.c.i:
	$(MAKE) -f CMakeFiles/sio_list_devices.dir/build.make CMakeFiles/sio_list_devices.dir/example/sio_list_devices.c.i
.PHONY : example/sio_list_devices.c.i

example/sio_list_devices.s: example/sio_list_devices.c.s

.PHONY : example/sio_list_devices.s

# target to generate assembly for a file
example/sio_list_devices.c.s:
	$(MAKE) -f CMakeFiles/sio_list_devices.dir/build.make CMakeFiles/sio_list_devices.dir/example/sio_list_devices.c.s
.PHONY : example/sio_list_devices.c.s

example/sio_microphone.o: example/sio_microphone.c.o

.PHONY : example/sio_microphone.o

# target to build an object file
example/sio_microphone.c.o:
	$(MAKE) -f CMakeFiles/sio_microphone.dir/build.make CMakeFiles/sio_microphone.dir/example/sio_microphone.c.o
.PHONY : example/sio_microphone.c.o

example/sio_microphone.i: example/sio_microphone.c.i

.PHONY : example/sio_microphone.i

# target to preprocess a source file
example/sio_microphone.c.i:
	$(MAKE) -f CMakeFiles/sio_microphone.dir/build.make CMakeFiles/sio_microphone.dir/example/sio_microphone.c.i
.PHONY : example/sio_microphone.c.i

example/sio_microphone.s: example/sio_microphone.c.s

.PHONY : example/sio_microphone.s

# target to generate assembly for a file
example/sio_microphone.c.s:
	$(MAKE) -f CMakeFiles/sio_microphone.dir/build.make CMakeFiles/sio_microphone.dir/example/sio_microphone.c.s
.PHONY : example/sio_microphone.c.s

example/sio_record.o: example/sio_record.c.o

.PHONY : example/sio_record.o

# target to build an object file
example/sio_record.c.o:
	$(MAKE) -f CMakeFiles/sio_record.dir/build.make CMakeFiles/sio_record.dir/example/sio_record.c.o
.PHONY : example/sio_record.c.o

example/sio_record.i: example/sio_record.c.i

.PHONY : example/sio_record.i

# target to preprocess a source file
example/sio_record.c.i:
	$(MAKE) -f CMakeFiles/sio_record.dir/build.make CMakeFiles/sio_record.dir/example/sio_record.c.i
.PHONY : example/sio_record.c.i

example/sio_record.s: example/sio_record.c.s

.PHONY : example/sio_record.s

# target to generate assembly for a file
example/sio_record.c.s:
	$(MAKE) -f CMakeFiles/sio_record.dir/build.make CMakeFiles/sio_record.dir/example/sio_record.c.s
.PHONY : example/sio_record.c.s

example/sio_sine.o: example/sio_sine.c.o

.PHONY : example/sio_sine.o

# target to build an object file
example/sio_sine.c.o:
	$(MAKE) -f CMakeFiles/sio_sine.dir/build.make CMakeFiles/sio_sine.dir/example/sio_sine.c.o
.PHONY : example/sio_sine.c.o

example/sio_sine.i: example/sio_sine.c.i

.PHONY : example/sio_sine.i

# target to preprocess a source file
example/sio_sine.c.i:
	$(MAKE) -f CMakeFiles/sio_sine.dir/build.make CMakeFiles/sio_sine.dir/example/sio_sine.c.i
.PHONY : example/sio_sine.c.i

example/sio_sine.s: example/sio_sine.c.s

.PHONY : example/sio_sine.s

# target to generate assembly for a file
example/sio_sine.c.s:
	$(MAKE) -f CMakeFiles/sio_sine.dir/build.make CMakeFiles/sio_sine.dir/example/sio_sine.c.s
.PHONY : example/sio_sine.c.s

src/channel_layout.o: src/channel_layout.c.o

.PHONY : src/channel_layout.o

# target to build an object file
src/channel_layout.c.o:
	$(MAKE) -f CMakeFiles/libsoundio_shared.dir/build.make CMakeFiles/libsoundio_shared.dir/src/channel_layout.c.o
	$(MAKE) -f CMakeFiles/libsoundio_static.dir/build.make CMakeFiles/libsoundio_static.dir/src/channel_layout.c.o
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/channel_layout.c.o
	$(MAKE) -f CMakeFiles/latency.dir/build.make CMakeFiles/latency.dir/src/channel_layout.c.o
.PHONY : src/channel_layout.c.o

src/channel_layout.i: src/channel_layout.c.i

.PHONY : src/channel_layout.i

# target to preprocess a source file
src/channel_layout.c.i:
	$(MAKE) -f CMakeFiles/libsoundio_shared.dir/build.make CMakeFiles/libsoundio_shared.dir/src/channel_layout.c.i
	$(MAKE) -f CMakeFiles/libsoundio_static.dir/build.make CMakeFiles/libsoundio_static.dir/src/channel_layout.c.i
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/channel_layout.c.i
	$(MAKE) -f CMakeFiles/latency.dir/build.make CMakeFiles/latency.dir/src/channel_layout.c.i
.PHONY : src/channel_layout.c.i

src/channel_layout.s: src/channel_layout.c.s

.PHONY : src/channel_layout.s

# target to generate assembly for a file
src/channel_layout.c.s:
	$(MAKE) -f CMakeFiles/libsoundio_shared.dir/build.make CMakeFiles/libsoundio_shared.dir/src/channel_layout.c.s
	$(MAKE) -f CMakeFiles/libsoundio_static.dir/build.make CMakeFiles/libsoundio_static.dir/src/channel_layout.c.s
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/channel_layout.c.s
	$(MAKE) -f CMakeFiles/latency.dir/build.make CMakeFiles/latency.dir/src/channel_layout.c.s
.PHONY : src/channel_layout.c.s

src/dummy.o: src/dummy.c.o

.PHONY : src/dummy.o

# target to build an object file
src/dummy.c.o:
	$(MAKE) -f CMakeFiles/libsoundio_shared.dir/build.make CMakeFiles/libsoundio_shared.dir/src/dummy.c.o
	$(MAKE) -f CMakeFiles/libsoundio_static.dir/build.make CMakeFiles/libsoundio_static.dir/src/dummy.c.o
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/dummy.c.o
	$(MAKE) -f CMakeFiles/latency.dir/build.make CMakeFiles/latency.dir/src/dummy.c.o
.PHONY : src/dummy.c.o

src/dummy.i: src/dummy.c.i

.PHONY : src/dummy.i

# target to preprocess a source file
src/dummy.c.i:
	$(MAKE) -f CMakeFiles/libsoundio_shared.dir/build.make CMakeFiles/libsoundio_shared.dir/src/dummy.c.i
	$(MAKE) -f CMakeFiles/libsoundio_static.dir/build.make CMakeFiles/libsoundio_static.dir/src/dummy.c.i
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/dummy.c.i
	$(MAKE) -f CMakeFiles/latency.dir/build.make CMakeFiles/latency.dir/src/dummy.c.i
.PHONY : src/dummy.c.i

src/dummy.s: src/dummy.c.s

.PHONY : src/dummy.s

# target to generate assembly for a file
src/dummy.c.s:
	$(MAKE) -f CMakeFiles/libsoundio_shared.dir/build.make CMakeFiles/libsoundio_shared.dir/src/dummy.c.s
	$(MAKE) -f CMakeFiles/libsoundio_static.dir/build.make CMakeFiles/libsoundio_static.dir/src/dummy.c.s
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/dummy.c.s
	$(MAKE) -f CMakeFiles/latency.dir/build.make CMakeFiles/latency.dir/src/dummy.c.s
.PHONY : src/dummy.c.s

src/os.o: src/os.c.o

.PHONY : src/os.o

# target to build an object file
src/os.c.o:
	$(MAKE) -f CMakeFiles/libsoundio_shared.dir/build.make CMakeFiles/libsoundio_shared.dir/src/os.c.o
	$(MAKE) -f CMakeFiles/libsoundio_static.dir/build.make CMakeFiles/libsoundio_static.dir/src/os.c.o
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/os.c.o
	$(MAKE) -f CMakeFiles/latency.dir/build.make CMakeFiles/latency.dir/src/os.c.o
.PHONY : src/os.c.o

src/os.i: src/os.c.i

.PHONY : src/os.i

# target to preprocess a source file
src/os.c.i:
	$(MAKE) -f CMakeFiles/libsoundio_shared.dir/build.make CMakeFiles/libsoundio_shared.dir/src/os.c.i
	$(MAKE) -f CMakeFiles/libsoundio_static.dir/build.make CMakeFiles/libsoundio_static.dir/src/os.c.i
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/os.c.i
	$(MAKE) -f CMakeFiles/latency.dir/build.make CMakeFiles/latency.dir/src/os.c.i
.PHONY : src/os.c.i

src/os.s: src/os.c.s

.PHONY : src/os.s

# target to generate assembly for a file
src/os.c.s:
	$(MAKE) -f CMakeFiles/libsoundio_shared.dir/build.make CMakeFiles/libsoundio_shared.dir/src/os.c.s
	$(MAKE) -f CMakeFiles/libsoundio_static.dir/build.make CMakeFiles/libsoundio_static.dir/src/os.c.s
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/os.c.s
	$(MAKE) -f CMakeFiles/latency.dir/build.make CMakeFiles/latency.dir/src/os.c.s
.PHONY : src/os.c.s

src/ring_buffer.o: src/ring_buffer.c.o

.PHONY : src/ring_buffer.o

# target to build an object file
src/ring_buffer.c.o:
	$(MAKE) -f CMakeFiles/libsoundio_shared.dir/build.make CMakeFiles/libsoundio_shared.dir/src/ring_buffer.c.o
	$(MAKE) -f CMakeFiles/libsoundio_static.dir/build.make CMakeFiles/libsoundio_static.dir/src/ring_buffer.c.o
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/ring_buffer.c.o
	$(MAKE) -f CMakeFiles/latency.dir/build.make CMakeFiles/latency.dir/src/ring_buffer.c.o
.PHONY : src/ring_buffer.c.o

src/ring_buffer.i: src/ring_buffer.c.i

.PHONY : src/ring_buffer.i

# target to preprocess a source file
src/ring_buffer.c.i:
	$(MAKE) -f CMakeFiles/libsoundio_shared.dir/build.make CMakeFiles/libsoundio_shared.dir/src/ring_buffer.c.i
	$(MAKE) -f CMakeFiles/libsoundio_static.dir/build.make CMakeFiles/libsoundio_static.dir/src/ring_buffer.c.i
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/ring_buffer.c.i
	$(MAKE) -f CMakeFiles/latency.dir/build.make CMakeFiles/latency.dir/src/ring_buffer.c.i
.PHONY : src/ring_buffer.c.i

src/ring_buffer.s: src/ring_buffer.c.s

.PHONY : src/ring_buffer.s

# target to generate assembly for a file
src/ring_buffer.c.s:
	$(MAKE) -f CMakeFiles/libsoundio_shared.dir/build.make CMakeFiles/libsoundio_shared.dir/src/ring_buffer.c.s
	$(MAKE) -f CMakeFiles/libsoundio_static.dir/build.make CMakeFiles/libsoundio_static.dir/src/ring_buffer.c.s
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/ring_buffer.c.s
	$(MAKE) -f CMakeFiles/latency.dir/build.make CMakeFiles/latency.dir/src/ring_buffer.c.s
.PHONY : src/ring_buffer.c.s

src/soundio.o: src/soundio.c.o

.PHONY : src/soundio.o

# target to build an object file
src/soundio.c.o:
	$(MAKE) -f CMakeFiles/libsoundio_shared.dir/build.make CMakeFiles/libsoundio_shared.dir/src/soundio.c.o
	$(MAKE) -f CMakeFiles/libsoundio_static.dir/build.make CMakeFiles/libsoundio_static.dir/src/soundio.c.o
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/soundio.c.o
	$(MAKE) -f CMakeFiles/latency.dir/build.make CMakeFiles/latency.dir/src/soundio.c.o
.PHONY : src/soundio.c.o

src/soundio.i: src/soundio.c.i

.PHONY : src/soundio.i

# target to preprocess a source file
src/soundio.c.i:
	$(MAKE) -f CMakeFiles/libsoundio_shared.dir/build.make CMakeFiles/libsoundio_shared.dir/src/soundio.c.i
	$(MAKE) -f CMakeFiles/libsoundio_static.dir/build.make CMakeFiles/libsoundio_static.dir/src/soundio.c.i
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/soundio.c.i
	$(MAKE) -f CMakeFiles/latency.dir/build.make CMakeFiles/latency.dir/src/soundio.c.i
.PHONY : src/soundio.c.i

src/soundio.s: src/soundio.c.s

.PHONY : src/soundio.s

# target to generate assembly for a file
src/soundio.c.s:
	$(MAKE) -f CMakeFiles/libsoundio_shared.dir/build.make CMakeFiles/libsoundio_shared.dir/src/soundio.c.s
	$(MAKE) -f CMakeFiles/libsoundio_static.dir/build.make CMakeFiles/libsoundio_static.dir/src/soundio.c.s
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/soundio.c.s
	$(MAKE) -f CMakeFiles/latency.dir/build.make CMakeFiles/latency.dir/src/soundio.c.s
.PHONY : src/soundio.c.s

src/util.o: src/util.c.o

.PHONY : src/util.o

# target to build an object file
src/util.c.o:
	$(MAKE) -f CMakeFiles/libsoundio_shared.dir/build.make CMakeFiles/libsoundio_shared.dir/src/util.c.o
	$(MAKE) -f CMakeFiles/libsoundio_static.dir/build.make CMakeFiles/libsoundio_static.dir/src/util.c.o
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/util.c.o
	$(MAKE) -f CMakeFiles/latency.dir/build.make CMakeFiles/latency.dir/src/util.c.o
.PHONY : src/util.c.o

src/util.i: src/util.c.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.c.i:
	$(MAKE) -f CMakeFiles/libsoundio_shared.dir/build.make CMakeFiles/libsoundio_shared.dir/src/util.c.i
	$(MAKE) -f CMakeFiles/libsoundio_static.dir/build.make CMakeFiles/libsoundio_static.dir/src/util.c.i
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/util.c.i
	$(MAKE) -f CMakeFiles/latency.dir/build.make CMakeFiles/latency.dir/src/util.c.i
.PHONY : src/util.c.i

src/util.s: src/util.c.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.c.s:
	$(MAKE) -f CMakeFiles/libsoundio_shared.dir/build.make CMakeFiles/libsoundio_shared.dir/src/util.c.s
	$(MAKE) -f CMakeFiles/libsoundio_static.dir/build.make CMakeFiles/libsoundio_static.dir/src/util.c.s
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/util.c.s
	$(MAKE) -f CMakeFiles/latency.dir/build.make CMakeFiles/latency.dir/src/util.c.s
.PHONY : src/util.c.s

test/backend_disconnect_recover.o: test/backend_disconnect_recover.c.o

.PHONY : test/backend_disconnect_recover.o

# target to build an object file
test/backend_disconnect_recover.c.o:
	$(MAKE) -f CMakeFiles/backend_disconnect_recover.dir/build.make CMakeFiles/backend_disconnect_recover.dir/test/backend_disconnect_recover.c.o
.PHONY : test/backend_disconnect_recover.c.o

test/backend_disconnect_recover.i: test/backend_disconnect_recover.c.i

.PHONY : test/backend_disconnect_recover.i

# target to preprocess a source file
test/backend_disconnect_recover.c.i:
	$(MAKE) -f CMakeFiles/backend_disconnect_recover.dir/build.make CMakeFiles/backend_disconnect_recover.dir/test/backend_disconnect_recover.c.i
.PHONY : test/backend_disconnect_recover.c.i

test/backend_disconnect_recover.s: test/backend_disconnect_recover.c.s

.PHONY : test/backend_disconnect_recover.s

# target to generate assembly for a file
test/backend_disconnect_recover.c.s:
	$(MAKE) -f CMakeFiles/backend_disconnect_recover.dir/build.make CMakeFiles/backend_disconnect_recover.dir/test/backend_disconnect_recover.c.s
.PHONY : test/backend_disconnect_recover.c.s

test/latency.o: test/latency.c.o

.PHONY : test/latency.o

# target to build an object file
test/latency.c.o:
	$(MAKE) -f CMakeFiles/latency.dir/build.make CMakeFiles/latency.dir/test/latency.c.o
.PHONY : test/latency.c.o

test/latency.i: test/latency.c.i

.PHONY : test/latency.i

# target to preprocess a source file
test/latency.c.i:
	$(MAKE) -f CMakeFiles/latency.dir/build.make CMakeFiles/latency.dir/test/latency.c.i
.PHONY : test/latency.c.i

test/latency.s: test/latency.c.s

.PHONY : test/latency.s

# target to generate assembly for a file
test/latency.c.s:
	$(MAKE) -f CMakeFiles/latency.dir/build.make CMakeFiles/latency.dir/test/latency.c.s
.PHONY : test/latency.c.s

test/overflow.o: test/overflow.c.o

.PHONY : test/overflow.o

# target to build an object file
test/overflow.c.o:
	$(MAKE) -f CMakeFiles/overflow.dir/build.make CMakeFiles/overflow.dir/test/overflow.c.o
.PHONY : test/overflow.c.o

test/overflow.i: test/overflow.c.i

.PHONY : test/overflow.i

# target to preprocess a source file
test/overflow.c.i:
	$(MAKE) -f CMakeFiles/overflow.dir/build.make CMakeFiles/overflow.dir/test/overflow.c.i
.PHONY : test/overflow.c.i

test/overflow.s: test/overflow.c.s

.PHONY : test/overflow.s

# target to generate assembly for a file
test/overflow.c.s:
	$(MAKE) -f CMakeFiles/overflow.dir/build.make CMakeFiles/overflow.dir/test/overflow.c.s
.PHONY : test/overflow.c.s

test/underflow.o: test/underflow.c.o

.PHONY : test/underflow.o

# target to build an object file
test/underflow.c.o:
	$(MAKE) -f CMakeFiles/underflow.dir/build.make CMakeFiles/underflow.dir/test/underflow.c.o
.PHONY : test/underflow.c.o

test/underflow.i: test/underflow.c.i

.PHONY : test/underflow.i

# target to preprocess a source file
test/underflow.c.i:
	$(MAKE) -f CMakeFiles/underflow.dir/build.make CMakeFiles/underflow.dir/test/underflow.c.i
.PHONY : test/underflow.c.i

test/underflow.s: test/underflow.c.s

.PHONY : test/underflow.s

# target to generate assembly for a file
test/underflow.c.s:
	$(MAKE) -f CMakeFiles/underflow.dir/build.make CMakeFiles/underflow.dir/test/underflow.c.s
.PHONY : test/underflow.c.s

test/unit_tests.o: test/unit_tests.c.o

.PHONY : test/unit_tests.o

# target to build an object file
test/unit_tests.c.o:
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/test/unit_tests.c.o
.PHONY : test/unit_tests.c.o

test/unit_tests.i: test/unit_tests.c.i

.PHONY : test/unit_tests.i

# target to preprocess a source file
test/unit_tests.c.i:
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/test/unit_tests.c.i
.PHONY : test/unit_tests.c.i

test/unit_tests.s: test/unit_tests.c.s

.PHONY : test/unit_tests.s

# target to generate assembly for a file
test/unit_tests.c.s:
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/test/unit_tests.c.s
.PHONY : test/unit_tests.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/strip"
	@echo "... doc"
	@echo "... sio_list_devices"
	@echo "... sio_sine"
	@echo "... libsoundio_shared"
	@echo "... libsoundio_static"
	@echo "... edit_cache"
	@echo "... coverage"
	@echo "... underflow"
	@echo "... sio_microphone"
	@echo "... sio_record"
	@echo "... install/local"
	@echo "... unit_tests"
	@echo "... overflow"
	@echo "... latency"
	@echo "... backend_disconnect_recover"
	@echo "... example/sio_list_devices.o"
	@echo "... example/sio_list_devices.i"
	@echo "... example/sio_list_devices.s"
	@echo "... example/sio_microphone.o"
	@echo "... example/sio_microphone.i"
	@echo "... example/sio_microphone.s"
	@echo "... example/sio_record.o"
	@echo "... example/sio_record.i"
	@echo "... example/sio_record.s"
	@echo "... example/sio_sine.o"
	@echo "... example/sio_sine.i"
	@echo "... example/sio_sine.s"
	@echo "... src/channel_layout.o"
	@echo "... src/channel_layout.i"
	@echo "... src/channel_layout.s"
	@echo "... src/dummy.o"
	@echo "... src/dummy.i"
	@echo "... src/dummy.s"
	@echo "... src/os.o"
	@echo "... src/os.i"
	@echo "... src/os.s"
	@echo "... src/ring_buffer.o"
	@echo "... src/ring_buffer.i"
	@echo "... src/ring_buffer.s"
	@echo "... src/soundio.o"
	@echo "... src/soundio.i"
	@echo "... src/soundio.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
	@echo "... test/backend_disconnect_recover.o"
	@echo "... test/backend_disconnect_recover.i"
	@echo "... test/backend_disconnect_recover.s"
	@echo "... test/latency.o"
	@echo "... test/latency.i"
	@echo "... test/latency.s"
	@echo "... test/overflow.o"
	@echo "... test/overflow.i"
	@echo "... test/overflow.s"
	@echo "... test/underflow.o"
	@echo "... test/underflow.i"
	@echo "... test/underflow.s"
	@echo "... test/unit_tests.o"
	@echo "... test/unit_tests.i"
	@echo "... test/unit_tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

